trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)/source-folder'
    Contents: '**'
    TargetFolder: '\\\\store1\\C$\\destination-folder'
    
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)/source-folder'
    Contents: '**'
    TargetFolder: '\\\\store2\\C$\\destination-folder'

# Thêm các bước tương tự cho các cửa hàng khác
